name: PythonAnywhere Redeploy Action
description: Redeploy a Django app to PythonAnywhere via SSH using Docker.
author: MiguelRizzi

branding:
  icon: upload-cloud
  color: blue

inputs:
  ssh_host:
    description: "SSH host for PythonAnywhere (default: ssh.pythonanywhere.com)"
    required: false
    default: "ssh.pythonanywhere.com"
  username:
    description: "Your PythonAnywhere username"
    required: true
  password:
    description: "Your PythonAnywhere password (required if no ssh_private_key)"
    required: false
  ssh_private_key:
    description: "SSH private key for authentication (required if no password)"
    required: false
  working_directory:
    description: "Target working directory on PythonAnywhere"
    required: true
  venv_directory:
    description: "Path to the Python virtual environment"
    required: true
  wsgi_file:
    description: "Path to the WSGI file to reload the app"
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.ssh_host }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.ssh_private_key }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.venv_directory }}
    - ${{ inputs.wsgi_file }}