name: Redeploy to PythonAnywhere

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Redeploy to PythonAnywhere
        uses: MiguelRizzi/pythonanywhere-deploy-ssh@v1.0.0
        with:
          # Optional: specify the SSH host (defaults to ssh.pythonanywhere.com)
          # ssh_host: ssh.eu.pythonanywhere.com

          # Required: your PythonAnywhere username
          username: ${{ secrets.PA_USERNAME }}

          # Required (if no ssh_private_key): your PythonAnywhere password
          # password: ${{ secrets.PA_PASSWORD }}

          # Required (if no password): SSH private key
          ssh_private_key: ${{ secrets.PA_SSH_PRIVATE_KEY }}

          # Required: target working directory on PythonAnywhere
          working_directory: ${{ secrets.PA_WORKING_DIRECTORY }}

          # Required: path to your virtual environment
          venv_directory: ${{ secrets.PA_VENV_DIRECTORY }}

          # Required: path to your WSGI file
          wsgi_file: /var/www/webapp_name_wsgi.py