name: Deploy to PythonAnywhere

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Redeploy to PythonAnywhere
        uses: MiguelRizzi/pythonanywhere-deploy-ssh@v1.0.0
        with:
          ssh_host: ssh.eu.pythonanywhere.com # Optional - defaults to ssh.pythonanywhere.com
          username: ${{ secrets.PA_USERNAME }} # Your PythonAnywhere username
          password: ${{ secrets.PA_PASSWORD }} # Your PythonAnywhere password
          working_directory: ${{ secrets.PA_WORKING_DIRECTORY }} # Target working directory on PythonAnywhere
          venv_directory: ${{ secrets.PA_VENV_DIRECTORY }} # Path to your virtual environment
          wsgi_file: /var/www/webapp_name_wsgi.py # Path to your WSGI file